# Generated by Django 4.1.3 on 2022-11-19 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='bith_date',
            new_name='birth_date',
        ),
    ]
