# Generated by Django 4.1.3 on 2022-11-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_rename_bith_date_customer_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='slug',
            field=models.SlugField(default='-'),
            preserve_default=False,
        ),
    ]
