# Generated by Django 4.1.3 on 2022-11-25 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_foodimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ['title']},
        ),
    ]
